/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "../index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "../src/**/*.{js,ts,jsx,tsx}",
    "../../src/**/*.{js,ts,jsx,tsx}",
    "**/*.{js,ts,jsx,tsx,html}"
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#41474e",
        "secondary-fixed": "#d3e4fe",
        "surface-bright": "#f7f9fb",
        "outline-variant": "#c2c6d4",
        "tertiary-container": "#596067",
        "on-primary-container": "#c8daff",
        "surface-container-low": "#f2f4f6",
        "on-primary-fixed": "#001b3d",
        "inverse-primary": "#a9c7ff",
        "on-primary": "#ffffff",
        "secondary": "#505f76",
        "surface-container": "#eceef0",
        "on-secondary-container": "#54647a",
        "on-primary-fixed-variant": "#00468c",
        "outline": "#727783",
        "inverse-on-surface": "#eff1f3",
        "secondary-fixed-dim": "#b7c8e1",
        "on-tertiary-container": "#d4dae2",
        "primary": "#00478d",
        "surface-container-high": "#e6e8ea",
        "surface-variant": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#42484f",
        "on-background": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#d6e3ff",
        "surface-dim": "#d8dadc",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#161c22",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "on-surface": "#191c1e",
        "tertiary-fixed": "#dde3eb",
        "primary-fixed-dim": "#a9c7ff",
        "on-secondary-fixed": "#0b1c30",
        "inverse-surface": "#2d3133",
        "error": "#ba1a1a",
        "background": "#f7f9fb",
        "secondary-container": "#d0e1fb",
        "error-container": "#ffdad6",
        "on-surface-variant": "#424752",
        "surface": "#f7f9fb",
        "tertiary-fixed-dim": "#c1c7cf",
        "surface-tint": "#005db6",
        "primary-container": "#005eb8"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "40px",
        "xl": "64px",
        "gutter": "24px",
        "max-width": "1280px",
        "md": "24px",
        "base": "8px",
        "sm": "12px",
        "xs": "4px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "headline-md": ["Manrope", "sans-serif"],
        "body-sm": ["Atkinson Hyperlegible Next", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "label-caps": ["Atkinson Hyperlegible Next", "sans-serif"],
        "body-md": ["Atkinson Hyperlegible Next", "sans-serif"],
        "body-lg": ["Atkinson Hyperlegible Next", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["30px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
